[package]
name = "reth-celo-chainspec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Celo chain specification for reth."

[lints]
workspace = true

[dependencies]
# reth
reth-chainspec.workspace = true
reth-celo-forks = { path = "../hardforks" }
reth-network-peers.workspace = true

# ethereum
alloy-chains.workspace = true
alloy-consensus.workspace = true
alloy-eips = { workspace = true, features = ["serde"] }
alloy-evm.workspace = true
alloy-genesis.workspace = true
alloy-primitives = { workspace = true, features = ["serde", "rlp"] }

# misc
eyre.workspace = true
once_cell.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
hex-literal = "0.4"

[features]
default = ["std"]
std = [
    "alloy-primitives/std",
    "alloy-genesis/std",
    "reth-chainspec/std",
    "once_cell/std",
    "serde/std",
    "serde_json/std",
]
