[package]
name = "reth-celo-forks"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Celo hardfork types for reth."

[lints]
workspace = true

[dependencies]
# reth
reth-ethereum-forks.workspace = true

# ethereum
alloy-hardforks.workspace = true

[features]
default = ["std"]
std = [
    "reth-ethereum-forks/std",
]
