[package]
name = "reth-celo-evm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Celo EVM configuration for reth, integrating celo-revm."

[lints]
workspace = true

[dependencies]
# reth
reth-celo-chainspec = { path = "../chainspec" }
reth-evm-ethereum = { workspace = true, features = ["std"] }

# celo
celo-revm = { workspace = true, features = ["std"] }
alloy-celo-evm = { workspace = true, features = ["std"] }

# revm
revm.workspace = true

[dev-dependencies]
reth-evm.workspace = true
reth-chainspec.workspace = true
reth-celo-chainspec = { path = "../chainspec" }
alloy-consensus.workspace = true
alloy-evm.workspace = true
op-revm.workspace = true

[features]
default = ["std"]
std = [
    "revm/std",
    "celo-revm/std",
    "alloy-celo-evm/std",
]
test-utils = [
    "reth-evm-ethereum/test-utils",
]
